resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: registry:5000/artifactory-resource
      tag: latest
      insecure: true

resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/spring-io/artifactory-resource
      branch: main
  - name: artifactory
    type: artifactory-resource
    source:
      uri: http://artifactory:8081/artifactory
      username: admin
      password: password
      build_name: test-build

jobs:
  - name: build
    plan:
      - get: git-repo
      - task: build
        file: git-repo/samples/simple/tasks/build.yml
      - put: artifactory
        params:
          repo: example-repo-local
          folder: test
          build_uri: "http://localhost:8080/artifactory/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
          build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
          debug: true
  - name: test
    plan:
      - get: artifactory
        trigger: true
        passed: [build]
