resource_types:
  - name: artifactory-resource
    type: docker-image
    source: {repository: springio/artifactory-resource, tag: ${nextVersion}}

resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/spring-io/artifactory-resource
      branch: main
  - name: artifactory
    type: artifactory-resource
    source:
      uri: ((sample-artifactory-uri))
      username: ((sample-artifactory-username))
      password: ((sample-artifactory-password))
      build_name: test-build

jobs:
  - name: build
    plan:
      - get: git-repo
      - task: build
        file: git-repo/samples/simple/tasks/build.yml
      - put: artifactory
        params:
          repo: example-repo-local
          folder: test
          build_uri: "((sample-concourse-uri))/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
          build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
  - name: test
    plan:
      - get: artifactory
        trigger: true
        passed: [build]
